language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
- gem install bundler -v 2.0.1
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true

  api_key:
    secure: "PFoELjZcIWE4bWa0pC2aSL9dyicbvqbqATGxNUxHNTaKCzvtc51ZjhudJBMvbVKeT2YDIbyNWTrkUSX45QQmVITr2P4gAZfZPa90TxBC8OqHIahS1dV/JPoyUsYn+CRYWrdISs9Si25IxD535BCMHQmnDwMIa5v0poH5hj+JhPx5F/E1+UNjgf5ITyncjRaa5HgVQr2xZrTShcC5qU3aEAtVgKcADMPeBlsmTMV1j/CCb2MgxuorAQlaYrcbyUd+aGZoRlc5ENg/iFcH1BJ9sWBC4HyX3Q7q3yE4rc0GgkWGrU1BJkIjzxgfPejRS+3SGT0WUEi1SUcg8FWBSWIBKlHQjTUH3LxjKTAoh4cfAIRERS7C/OuKFEDerlCe5byCKVb57r/Yl0WzZMc1gHBasj/NJ6vQjvdDueng2R5YDU3ZCUqdxiGkFql+KqY/ZX5fMO1W7GtzltI4ac9HyI9TI5UuGLVgedWzm/bCz8FBNKJm8a8icwO+qimAKVSgNDAAhhPdpCdUj30XIGBcJwqyuWdLM1rlaWrKtx84mZRvm8QCoZCwLsvcFEYPRwi6Cr/Fn4bYyB3cpvWlb/NM8GeT04X6rVPSGmp+wdHjRL91dlxehHL/GL8bdtLQHtJ+4xi7jMml1dX0qzJ28rcFVtIKethnFx1AgHkqwm0uKqLI6aY="
  on:
    branch: master
