title: 8Bits/Code
url: https://8bits-code.github.io
author: 8bits-code
email: oitobits.code@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Conteúdo para quem está aprendendo a programar em Java ou Python, você
  pode nós encontrar no YouTube como 8Bits Code, vídeos toda semana.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 4
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: 8bits-code-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/bitbrain_
      icon: twitter-square
      color: cyan
    - url: https://bitbrain.itch.io
      icon: itch-io
      color: red
    - url: https://github.com/8bits-code
      icon: github-square
      color: purple
    - url: https://www.youtube.com/channel/UC6qRe3cEGMY10GTg6rH_E9w?sub_confirmation=1
      icon: youtube
      color: red

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: 8bits-code
